name: CTF
version: 2.0
author: Perelan
main: io.riat.CTF.CTF
api-version: 1.15
depends: Essentials
commands:
  createteam:
    description: Create your team
    usage: /createteam <WHITE - ORANGE - MAGENTA - YELLOW - LIME - PINK - GRAY - CYAN - PURPLE - BLUE - BROWN - GREEN - RED - BLACK>
  inviteteam:
    description: Invite a player to your team
    usage: /inviteteam <PLAYER>
  leaveteam:
    description: Leave the team
    usage: /leaveteam <YES>
  flagteam:
    description: Get a new team flag
    /usage: /flagteam