name: CTF
version: 1
author: RIAT
main: io.riat.CTF.CTF
api-version: 1.13
commands:
  createteam:
    description: Create your team
    usage: /createteam <WHITE - ORANGE - MAGENTA - YELLOW - LIME - PINK - GRAY - CYAN - PURPLE - BLUE - BROWN - GREEN - RED - BLACK>
  inviteteam:
    description: Invite a player to your team
    usage: /inviteteam <PLAYER>
  leaveteam:
    description: Leave the team
    usage: /leaveteam <YES>